###get users
GET http://localhost:3000/api/users
Content-Type: application/json

### create users
POST  https://omsnepal.com/api/users
Content-Type: application/json

{
    "email" : "ak@g.co",
    "name":"test"
}

### 
GET https://yuemi.com.np/api/products

### get categories
GET http://localhost:3000/api/categories
Content-Type: application/json

### get prducts
GET http://localhost:3000/api/products
Content-Type: application/json

###
GET https://gargdental.omsok.com/api/v1/banners/mobile