import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import { Toaster } from "react-hot-toast";
// import CookieConsentBanner from "@/components/CookieConsentBanner";
// import ClientLayout from "@/components/ClientLayut";
// import FooterBar from "@/components/FooterBar";
// import HeaderBar from "@/components/HeaderBar";
// import CartSidebar from  "@/components/CartSidebar";
import LayoutWrapper from "@/components/LayoutWrapper";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Yuemi Ecosystem Nepal",
  description: "Generated by Global Tech Nepal Pvt Ltd",
    icons: {
    icon: "/yumei_logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
         <head>
        <link rel="icon" href="/yumei_logo.png" />
       
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <LayoutWrapper>{children}</LayoutWrapper>
      </body>
    </html>
  );
}
